
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1compiladores12022.JflexYCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICAR = 8;
  public static final int DIVIDIR = 7;
  public static final int PUNTOYCOMA = 3;
  public static final int DECIMAL = 29;
  public static final int ETIQUETAS = 23;
  public static final int EJECUTAR = 20;
  public static final int PORCENTAJE = 31;
  public static final int TIPO = 25;
  public static final int VALORES = 24;
  public static final int BARRAS = 16;
  public static final int COMA = 4;
  public static final int TOTAL = 26;
  public static final int EOF = 0;
  public static final int DEF = 15;
  public static final int PIE = 17;
  public static final int CANTIDAD = 32;
  public static final int EXTRA = 27;
  public static final int RESTAR = 6;
  public static final int DOBLEPUNTO = 2;
  public static final int PARENTESIS_C = 10;
  public static final int error = 1;
  public static final int PARENTESIS_A = 9;
  public static final int LLAVE_C = 14;
  public static final int EJEY = 22;
  public static final int LLAVE_A = 13;
  public static final int EJEX = 21;
  public static final int TEXT = 30;
  public static final int ENTERO = 28;
  public static final int SUMAR = 5;
  public static final int CORCHETE_C = 12;
  public static final int UNIR = 19;
  public static final int CORCHETE_A = 11;
  public static final int TITULO = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOBLEPUNTO",
  "PUNTOYCOMA",
  "COMA",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "LLAVE_A",
  "LLAVE_C",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "UNIR",
  "EJECUTAR",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "ENTERO",
  "DECIMAL",
  "TEXT",
  "PORCENTAJE",
  "CANTIDAD"
  };
}

